% Input: distribution and image coefficients.
% Output: squared error of spectral algorithm for the case of exact moments
% given.
function min_err_spectral = asymptoticSpectralError(Q, B, a_symm_1B, rho_hat_symm_2B, resolution_error)

[~, ~, min_err_spectral] = runNumericalExperiment('B', B, 'Q', Q, 'sigma', 0,...
    'rho_hat_symm_2B', rho_hat_symm_2B,...
    'a_symm_1B', a_symm_1B, 'moment_type', "analytical",...
    'resolution_error', resolution_error,...
    'only_one_algorithm', 'Spectral');

end